#################################### global configure #######################################
username: zcoljefe
title: Zcoljefe's Blog
description: Progress is not created by contented people!

encoding: utf-8
theme: jekyll-theme-architect

