#################################### global configure #######################################
username: zcoljefe
title: Zcoljefe's Blog
description: Progress is not created by contented people!

excerpt_separator: <!--more-->

encoding: utf-8
theme: jekyll-theme-cayman

#导航栏
nav:
  - text: 首 页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html

#分页
paginate: 4
paginate_path: /page:num
plugins: [jekyll-paginate]